name: Build Content

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Configure pip caching
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install dependencies
        run: |
          python -m pip install -r script/requirements.txt
      
      - name: Build Content
        run: |
          python script/generate.py
      
      - name: commit corpus
        run: |
          git diff
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "github-actions"
          git add -A
          git commit -m "update corpus" || exit 0
          git push
